### ISSUE TITLE
is_control error

### ISSUE THREAD

**Issue by RedSoxFan04** [siverv/rss-plugin#1]
I tried the first step of the installation instructions, and I received the following error message: `error[E0599]: no method named `is_control` found for type `char` in the current scope`

**Comment by siverv** [comment]
At a guess, it's because I've forgotten to include the prerequisites.
I'll look into which packages exactly are required, but it's probably:
- libgtk-3-dev
- libxfce4panel-2.0-dev
- libxfce4ui-2-dev

**Comment by siverv** [comment]
I've now updated the Readme with all the installs I needed when building the plugin on a fresh Xubuntu install. I didn't encounter your exact error, but hopefully it will be solved. I've also added a 'known problems' part, with the problems I encountered, and their workaround until I get time to fix them properly.

**Comment by RedSoxFan04** [comment]
Thanks!
